// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
	"time"
)

const getItemDetail = `-- name: GetItemDetail :one
SELECT id, kind, name, maker, created_at FROM items WHERE id = ?
`

type GetItemDetailRow struct {
	ID        uint64
	Kind      string
	Name      string
	Maker     string
	CreatedAt time.Time
}

func (q *Queries) GetItemDetail(ctx context.Context, id uint64) (GetItemDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getItemDetail, id)
	var i GetItemDetailRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Maker,
		&i.CreatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT i.id, i.kind, i.name, i.maker, i.created_at,
       COUNT(r.photo_id) AS photo_count
FROM items i
LEFT JOIN photo_replica r ON r.gear_item_id = i.id
GROUP BY i.id, i.kind, i.name, i.maker, i.created_at
ORDER BY i.id DESC
LIMIT ?
`

type ListItemsRow struct {
	ID         uint64
	Kind       string
	Name       string
	Maker      string
	CreatedAt  time.Time
	PhotoCount int64
}

// 一覧は行ごとに作例の件数を出す。photo へ行ごとに問い合わせると HTTP 越しの N+1 になるため、
// ここだけ ReplicaView（photo_replica）を読む（internal-01 §ReplicaView の昇格条件）。
// 同一 database 内の JOIN であり、他ドメインの**テーブル**を参照しているわけではない
// （複製の正は photo。イベント契約にのみ依存する）。
func (q *Queries) ListItems(ctx context.Context, limit int32) ([]ListItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Maker,
			&i.CreatedAt,
			&i.PhotoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
