// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type Item struct {
	ID uint64
	// camera / lens / tripod など。検証はアプリ側
	Kind string
	// 機種の表示名
	Name string
	// メーカー名（任意）
	Maker string
	// 投稿者の subject
	CreatedBy string
	CreatedAt time.Time
}
