// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

// 処理済みイベント。業務処理と同一 tx で記録し、重複配送を無害化する
type Inbox struct {
	// 送信側が採番したイベントID
	EventID    string
	EventType  string
	ReceivedAt time.Time
}

type Item struct {
	ID uint64
	// camera / lens / tripod など。検証はアプリ側
	Kind string
	// 機種の表示名
	Name string
	// メーカー名（任意）
	Maker string
	// 投稿者の subject
	CreatedBy string
	CreatedAt time.Time
}
