// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_replica.sql

package sqlcgen

import (
	"context"
	"time"
)

const checksumPhotoReplica = `-- name: ChecksumPhotoReplica :one
SELECT COALESCE(MD5(GROUP_CONCAT(
    CONCAT_WS(':', photo_id, gear_item_id, caption, photo_created_at)
    ORDER BY photo_id SEPARATOR '|')), '') AS fingerprint
FROM photo_replica
`

// 再構築結果の一致を機械で比べるための指紋（check #10）。
// replicated_at は再構築で必ず変わるので含めない——**変わってよい列を含めると
// 「一致」が絶対に成立しない検査になる**
func (q *Queries) ChecksumPhotoReplica(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, checksumPhotoReplica)
	var fingerprint interface{}
	err := row.Scan(&fingerprint)
	return fingerprint, err
}

const countPhotoReplica = `-- name: CountPhotoReplica :one
SELECT COUNT(*) FROM photo_replica
`

func (q *Queries) CountPhotoReplica(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPhotoReplica)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePhotoReplica = `-- name: DeletePhotoReplica :exec
DELETE FROM photo_replica WHERE photo_id = ?
`

// 存在しない行の削除も無害（再配送・再生で複数回届く前提）
func (q *Queries) DeletePhotoReplica(ctx context.Context, photoID uint64) error {
	_, err := q.db.ExecContext(ctx, deletePhotoReplica, photoID)
	return err
}

const truncatePhotoReplica = `-- name: TruncatePhotoReplica :exec
DELETE FROM photo_replica
`

// 再構築の起点。管理コマンドからのみ呼ぶ
func (q *Queries) TruncatePhotoReplica(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncatePhotoReplica)
	return err
}

const upsertPhotoReplica = `-- name: UpsertPhotoReplica :exec

INSERT INTO photo_replica (photo_id, gear_item_id, caption, photo_created_at)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    gear_item_id = VALUES(gear_item_id),
    caption = VALUES(caption),
    photo_created_at = VALUES(photo_created_at)
`

type UpsertPhotoReplicaParams struct {
	PhotoID        uint64
	GearItemID     uint64
	Caption        string
	PhotoCreatedAt time.Time
}

// ReplicaView（photo の公開データの複製）の書き込みと再構築。
// 読み取りは readmodel 側のクエリが JOIN で行う（表示は Read Model の役目）。
// 同一イベントの再適用が無害であること（自然冪等）を SQL 側でも担保する。
// inbox が主たる防御だが、再構築（replay）は inbox を空にしてから流すため、
// ここが冪等でないと再構築のたびに重複キーで落ちる
func (q *Queries) UpsertPhotoReplica(ctx context.Context, arg UpsertPhotoReplicaParams) error {
	_, err := q.db.ExecContext(ctx, upsertPhotoReplica,
		arg.PhotoID,
		arg.GearItemID,
		arg.Caption,
		arg.PhotoCreatedAt,
	)
	return err
}
