// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createItem = `-- name: CreateItem :execresult
INSERT INTO items (kind, name, maker, created_by) VALUES (?, ?, ?, ?)
`

type CreateItemParams struct {
	Kind      string
	Name      string
	Maker     string
	CreatedBy string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createItem,
		arg.Kind,
		arg.Name,
		arg.Maker,
		arg.CreatedBy,
	)
}

const getItem = `-- name: GetItem :one
SELECT id, kind, name, maker, created_by, created_at FROM items WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id uint64) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Maker,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
