// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

// 処理済みイベント。業務処理と同一 tx で記録し、重複配送を無害化する
type Inbox struct {
	// 送信側が採番したイベントID
	EventID    string
	EventType  string
	ReceivedAt time.Time
}

type Item struct {
	ID uint64
	// camera / lens / tripod など。検証はアプリ側
	Kind string
	// 機種の表示名
	Name string
	// メーカー名（任意）
	Maker string
	// 投稿者の subject
	CreatedBy string
	CreatedAt time.Time
}

// 写真と機材の紐付け（同期コマンドの受理記録。冪等キーが正）
type PhotoLink struct {
	// photo が採番する冪等キー（Idempotency-Key）
	LinkKey string
	// 紐付け先の機材
	ItemID uint64
	// photo サービスの写真ID（値として持つだけ。FK は張らない）
	PhotoID uint64
	// linked / rejected
	Status string
	// rejected の理由（機械可読の短い語）
	Reason    string
	CreatedAt time.Time
}

// 他ドメイン（photo）の公開データの読み取り専用の複製。表示専用
type PhotoReplica struct {
	// photo サービスの ID（正は相手）
	PhotoID uint64
	// どの機材の作例か
	GearItemID uint64
	Caption    string
	// photo 側の作成時刻（並び順に使う）
	PhotoCreatedAt time.Time
	ReplicatedAt   time.Time
}
