// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_links.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getPhotoLink = `-- name: GetPhotoLink :one
SELECT link_key, item_id, photo_id, status, reason FROM photo_links WHERE link_key = ?
`

type GetPhotoLinkRow struct {
	LinkKey string
	ItemID  uint64
	PhotoID uint64
	Status  string
	Reason  string
}

func (q *Queries) GetPhotoLink(ctx context.Context, linkKey string) (GetPhotoLinkRow, error) {
	row := q.db.QueryRowContext(ctx, getPhotoLink, linkKey)
	var i GetPhotoLinkRow
	err := row.Scan(
		&i.LinkKey,
		&i.ItemID,
		&i.PhotoID,
		&i.Status,
		&i.Reason,
	)
	return i, err
}

const insertPhotoLink = `-- name: InsertPhotoLink :execresult

INSERT IGNORE INTO photo_links (link_key, item_id, photo_id, status, reason)
VALUES (?, ?, ?, ?, ?)
`

type InsertPhotoLinkParams struct {
	LinkKey string
	ItemID  uint64
	PhotoID uint64
	Status  string
	Reason  string
}

// 同期コマンド「使用機材の紐付け」の受理記録（4.4）。
// 冪等: 同じ link_key の再送は INSERT IGNORE が弾き（RowsAffected=0）、
// 呼び出し側は既存の結果を返す。UPDATE しないのが要点——リトライで結果が変わると
// 「1回目 rejected、2回目 linked」のような不定になる
func (q *Queries) InsertPhotoLink(ctx context.Context, arg InsertPhotoLinkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPhotoLink,
		arg.LinkKey,
		arg.ItemID,
		arg.PhotoID,
		arg.Status,
		arg.Reason,
	)
}

const itemExists = `-- name: ItemExists :one
SELECT EXISTS(SELECT 1 FROM items WHERE id = ?)
`

func (q *Queries) ItemExists(ctx context.Context, id uint64) (bool, error) {
	row := q.db.QueryRowContext(ctx, itemExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
