// Package photoclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package photoclient

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Error defines model for Error.
type Error struct {
	// Code 機械可読のエラーコード
	//
	// Examples: photo.not_found
	Code string `json:"code"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	//
	// Examples: Property foo is required but is missing.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	//
	// Examples: https://example.com/error-log/abc123
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	//
	// Examples: 400
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	//
	// Examples: Bad Request
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	//
	// Examples: https://example.com/errors/example
	Type *string `json:"type,omitempty"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ListPhotosByGearItemOutputBody defines model for ListPhotosByGearItemOutputBody.
type ListPhotosByGearItemOutputBody struct {
	// Photos 作例の一覧
	Photos *[]ServicePhoto `json:"photos"`
}

// ServicePhoto defines model for ServicePhoto.
type ServicePhoto struct {
	// Caption キャプション
	Caption string `json:"caption"`

	// CreatedAt 投稿時刻
	CreatedAt time.Time `json:"created_at"`

	// GearItemId 使用機材（gear の item ID）
	GearItemId *int64 `json:"gear_item_id,omitempty"`

	// Id 写真ID
	//
	// Examples: 1
	Id int64 `json:"id"`

	// ImageUrl 画像取得用の署名付きURL。期限付き
	ImageUrl *string `json:"image_url,omitempty"`

	// OwnerId 投稿者のSubject
	//
	// Examples: u_01H...
	OwnerId string `json:"owner_id"`
}

// ListPhotosByGearItemParams defines parameters for ListPhotosByGearItem.
type ListPhotosByGearItemParams struct {
	// Limit 取得件数
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListPhotosByGearItem 機材に紐づく作例の一覧（サービス間）
	//
	// 呼び出し側の N+1 を避けるための Batch 取得API。.
	//
	// Corresponds with GET /gear-items/{gear_item_id}/photos (the `ListPhotosByGearItem` operationId).
	ListPhotosByGearItem(ctx context.Context, gearItemId int64, params *ListPhotosByGearItemParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPhotoForService 写真を取得する（サービス間）
	//
	// gear が作例の表示に用いる。公開データのみを返す。.
	//
	// Corresponds with GET /photos/{id} (the `GetPhotoForService` operationId).
	GetPhotoForService(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListPhotosByGearItem 機材に紐づく作例の一覧（サービス間）
//
// 呼び出し側の N+1 を避けるための Batch 取得API。.
//
// Corresponds with GET /gear-items/{gear_item_id}/photos (the `ListPhotosByGearItem` operationId).
func (c *Client) ListPhotosByGearItem(ctx context.Context, gearItemId int64, params *ListPhotosByGearItemParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPhotosByGearItemRequest(c.Server, gearItemId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPhotoForService 写真を取得する（サービス間）
//
// gear が作例の表示に用いる。公開データのみを返す。.
//
// Corresponds with GET /photos/{id} (the `GetPhotoForService` operationId).
func (c *Client) GetPhotoForService(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPhotoForServiceRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPhotosByGearItemRequest constructs an http.Request for the ListPhotosByGearItem method
func NewListPhotosByGearItemRequest(server string, gearItemId int64, params *ListPhotosByGearItemParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "gear_item_id", gearItemId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/gear-items/%s/photos", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPhotoForServiceRequest constructs an http.Request for the GetPhotoForService method
func NewGetPhotoForServiceRequest(server string, id int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/photos/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListPhotosByGearItemWithResponse 機材に紐づく作例の一覧（サービス間）
	//
	// 呼び出し側の N+1 を避けるための Batch 取得API。.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /gear-items/{gear_item_id}/photos (the `ListPhotosByGearItem` operationId).
	ListPhotosByGearItemWithResponse(ctx context.Context, gearItemId int64, params *ListPhotosByGearItemParams, reqEditors ...RequestEditorFn) (*ListPhotosByGearItemResponse, error)

	// GetPhotoForServiceWithResponse 写真を取得する（サービス間）
	//
	// gear が作例の表示に用いる。公開データのみを返す。.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /photos/{id} (the `GetPhotoForService` operationId).
	GetPhotoForServiceWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*GetPhotoForServiceResponse, error)
}

type ListPhotosByGearItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListPhotosByGearItemOutputBody
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListPhotosByGearItemResponse) GetJSON200() *ListPhotosByGearItemOutputBody {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ListPhotosByGearItemResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r ListPhotosByGearItemResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r ListPhotosByGearItemResponse) GetApplicationproblemJSON422() *Error {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ListPhotosByGearItemResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r ListPhotosByGearItemResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListPhotosByGearItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPhotosByGearItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPhotosByGearItemResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPhotoForServiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ServicePhoto
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *Error
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPhotoForServiceResponse) GetJSON200() *ServicePhoto {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetPhotoForServiceResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r GetPhotoForServiceResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetPhotoForServiceResponse) GetApplicationproblemJSON404() *Error {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r GetPhotoForServiceResponse) GetApplicationproblemJSON422() *Error {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetPhotoForServiceResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetPhotoForServiceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPhotoForServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPhotoForServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPhotoForServiceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListPhotosByGearItemWithResponse 機材に紐づく作例の一覧（サービス間）
//
// 呼び出し側の N+1 を避けるための Batch 取得API。.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /gear-items/{gear_item_id}/photos (the `ListPhotosByGearItem` operationId).
func (c *ClientWithResponses) ListPhotosByGearItemWithResponse(ctx context.Context, gearItemId int64, params *ListPhotosByGearItemParams, reqEditors ...RequestEditorFn) (*ListPhotosByGearItemResponse, error) {
	rsp, err := c.ListPhotosByGearItem(ctx, gearItemId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPhotosByGearItemResponse(rsp)
}

// GetPhotoForServiceWithResponse 写真を取得する（サービス間）
//
// gear が作例の表示に用いる。公開データのみを返す。.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /photos/{id} (the `GetPhotoForService` operationId).
func (c *ClientWithResponses) GetPhotoForServiceWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*GetPhotoForServiceResponse, error) {
	rsp, err := c.GetPhotoForService(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPhotoForServiceResponse(rsp)
}

// ParseListPhotosByGearItemResponse parses an HTTP response from a ListPhotosByGearItemWithResponse call
func ParseListPhotosByGearItemResponse(rsp *http.Response) (*ListPhotosByGearItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPhotosByGearItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListPhotosByGearItemOutputBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetPhotoForServiceResponse parses an HTTP response from a GetPhotoForServiceWithResponse call
func ParseGetPhotoForServiceResponse(rsp *http.Response) (*GetPhotoForServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPhotoForServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServicePhoto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}
