// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PhotosStatus string

const (
	PhotosStatusPendingUpload PhotosStatus = "pending_upload"
	PhotosStatusReady         PhotosStatus = "ready"
)

func (e *PhotosStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotosStatus(s)
	case string:
		*e = PhotosStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotosStatus: %T", src)
	}
	return nil
}

type NullPhotosStatus struct {
	PhotosStatus PhotosStatus
	Valid        bool // Valid is true if PhotosStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotosStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PhotosStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotosStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotosStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotosStatus), nil
}

type PhotosVisibility string

const (
	PhotosVisibilityPrivate PhotosVisibility = "private"
	PhotosVisibilityPublic  PhotosVisibility = "public"
)

func (e *PhotosVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotosVisibility(s)
	case string:
		*e = PhotosVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotosVisibility: %T", src)
	}
	return nil
}

type NullPhotosVisibility struct {
	PhotosVisibility PhotosVisibility
	Valid            bool // Valid is true if PhotosVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotosVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.PhotosVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotosVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotosVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotosVisibility), nil
}

type Photo struct {
	ID           uint64
	OwnerSubject string
	Caption      string
	Visibility   PhotosVisibility
	GearItemID   sql.NullInt64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ObjectKey    sql.NullString
	ContentType  sql.NullString
	SizeBytes    sql.NullInt64
	Status       PhotosStatus
}
