// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPhoto = `-- name: CreatePhoto :execresult

INSERT INTO photos (owner_subject, caption, visibility, gear_item_id)
VALUES (?, ?, ?, ?)
`

type CreatePhotoParams struct {
	OwnerSubject string
	Caption      string
	Visibility   PhotosVisibility
	GearItemID   sql.NullInt64
}

// コマンド側（Entity の復元・保存）のクエリ。参照できるのは自ドメイン（photo）のテーブルのみ。
func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPhoto,
		arg.OwnerSubject,
		arg.Caption,
		arg.Visibility,
		arg.GearItemID,
	)
}

const deletePhotosByOwner = `-- name: DeletePhotosByOwner :execresult
DELETE FROM photos WHERE owner_subject = ?
`

func (q *Queries) DeletePhotosByOwner(ctx context.Context, ownerSubject string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePhotosByOwner, ownerSubject)
}

const getPhotoForUpdate = `-- name: GetPhotoForUpdate :one
SELECT id, owner_subject, caption, visibility, gear_item_id, created_at, updated_at FROM photos WHERE id = ? FOR UPDATE
`

func (q *Queries) GetPhotoForUpdate(ctx context.Context, id uint64) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhotoForUpdate, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerSubject,
		&i.Caption,
		&i.Visibility,
		&i.GearItemID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhoto = `-- name: UpdatePhoto :exec
UPDATE photos SET caption = ?, visibility = ?, gear_item_id = ? WHERE id = ?
`

type UpdatePhotoParams struct {
	Caption    string
	Visibility PhotosVisibility
	GearItemID sql.NullInt64
	ID         uint64
}

func (q *Queries) UpdatePhoto(ctx context.Context, arg UpdatePhotoParams) error {
	_, err := q.db.ExecContext(ctx, updatePhoto,
		arg.Caption,
		arg.Visibility,
		arg.GearItemID,
		arg.ID,
	)
	return err
}
