/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 写真の一覧（Read Model）
         * @description ListAccessible で得たIDを WHERE IN で絞るため、他人の写真は不可視。
         */
        get: operations["ListPhotos"];
        put?: never;
        /** 写真を投稿する */
        post: operations["CreatePhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 写真の詳細（Read Model） */
        get: operations["GetPhotoDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/photos/{id}:commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 画像のアップロード完了を確定する
         * @description 署名URLへの PUT が終わったら呼ぶ。画像の実体が確認できなければ確定しない。
         */
        post: operations["CommitPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/photos/{id}:publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 写真を公開する
         * @description 純粋な状態遷移のため :verb を使う。
         */
        post: operations["PublishPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePhotoInputBody: {
            /** @description キャプション */
            caption: string;
            /**
             * @description アップロードする画像の種類
             * @example image/jpeg
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp" | "image/avif";
            /**
             * Format: int64
             * @description 使用機材（gear の item ID）。値を保存するだけで、gear 側への問い合わせや紐付けは行わない
             */
            gear_item_id?: number;
            /**
             * @description 公開状態
             * @default private
             * @enum {string}
             */
            visibility: "private" | "public";
        };
        CreatePhotoOutputBody: {
            /**
             * @description キャプション
             * @example 朝の光
             */
            caption: string;
            /**
             * Format: date-time
             * @description 投稿時刻
             */
            created_at: string;
            /**
             * Format: int64
             * @description 使用機材（gear の item ID）
             * @example 42
             */
            gear_item_id?: number;
            /**
             * Format: int64
             * @description 写真ID
             * @example 1
             */
            id: number;
            /** @description 画像取得用の署名付きURL。期限付き */
            image_url?: string;
            /**
             * @description 投稿者のSubject
             * @example u_01H...
             */
            owner_id: string;
            /**
             * Format: int64
             * @description 画像のバイト数
             */
            size_bytes?: number;
            /**
             * @description 画像のアップロード状態
             * @example ready
             * @enum {string}
             */
            status: "pending_upload" | "ready";
            /**
             * Format: date-time
             * @description 署名URLの有効期限
             */
            upload_expires_at: string;
            /** @description 画像アップロード用の署名付きURL。Content-Type ヘッダを content_type と同じ値で送る */
            upload_url: string;
            /**
             * @description 公開状態
             * @example public
             * @enum {string}
             */
            visibility: "private" | "public";
        };
        Error: {
            /**
             * @description 機械可読のエラーコード
             * @example photo.not_found
             */
            code: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ListPhotosOutputBody: {
            /** @description 主体が今この一覧へ写真を投稿できるか。投稿の一時停止中などは false */
            can_create: boolean;
            /** @description 写真の一覧 */
            photos: components["schemas"]["Photo"][] | null;
        };
        Photo: {
            /**
             * @description キャプション
             * @example 朝の光
             */
            caption: string;
            /**
             * Format: date-time
             * @description 投稿時刻
             */
            created_at: string;
            /**
             * Format: int64
             * @description 使用機材（gear の item ID）
             * @example 42
             */
            gear_item_id?: number;
            /**
             * Format: int64
             * @description 写真ID
             * @example 1
             */
            id: number;
            /** @description 画像取得用の署名付きURL。期限付き */
            image_url?: string;
            /**
             * @description 投稿者のSubject
             * @example u_01H...
             */
            owner_id: string;
            /**
             * Format: int64
             * @description 画像のバイト数
             */
            size_bytes?: number;
            /**
             * @description 画像のアップロード状態
             * @example ready
             * @enum {string}
             */
            status: "pending_upload" | "ready";
            /**
             * @description 公開状態
             * @example public
             * @enum {string}
             */
            visibility: "private" | "public";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListPhotos: {
        parameters: {
            query?: {
                /** @description 公開状態で絞る */
                visibility?: "private" | "public";
                /** @description 取得件数 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPhotosOutputBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    CreatePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhotoInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePhotoOutputBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    GetPhotoDetail: {
        parameters: {
            query?: {
                /** @description 作成直後でも確実に見えるよう、認可判定の鮮度を上げる */
                fresh?: boolean;
            };
            header?: never;
            path: {
                /** @description 写真ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    CommitPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 写真ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    PublishPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 写真ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
}
