/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 機材の一覧 */
        get: operations["ListItems"];
        put?: never;
        /**
         * 機材を投稿する
         * @description カタログは共有財。認証済みであれば誰でも投稿できる。
         */
        post: operations["CreateItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 機材の詳細と作例
         * @description 作例は photo サービスの internal API から M2M で引く。取得に失敗したら詳細ごと失敗にする（半端な応答を作らない）。
         */
        get: operations["GetItemDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateItemInputBody: {
            /**
             * @description 分類
             * @enum {string}
             */
            kind: "camera" | "lens" | "tripod" | "filter" | "bag" | "accessory";
            /** @description メーカー名 */
            maker?: string;
            /** @description 機種名 */
            name: string;
        };
        Error: {
            /**
             * @description 機械可読のエラーコード
             * @example photo.not_found
             */
            code: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        GetItemDetailOutputBody: {
            /**
             * Format: date-time
             * @description 投稿時刻
             */
            created_at?: string;
            /**
             * Format: int64
             * @description 機材ID
             * @example 1
             */
            id: number;
            /**
             * @description 分類
             * @example camera
             */
            kind: string;
            /**
             * @description メーカー名
             * @example FUJIFILM
             */
            maker?: string;
            /**
             * @description 機種名
             * @example X-T5
             */
            name: string;
            /** @description 作例（公開済みの写真） */
            photos: components["schemas"]["PhotoRef"][] | null;
        };
        Item: {
            /**
             * Format: date-time
             * @description 投稿時刻
             */
            created_at?: string;
            /**
             * Format: int64
             * @description 機材ID
             * @example 1
             */
            id: number;
            /**
             * @description 分類
             * @example camera
             */
            kind: string;
            /**
             * @description メーカー名
             * @example FUJIFILM
             */
            maker?: string;
            /**
             * @description 機種名
             * @example X-T5
             */
            name: string;
        };
        ListItemsOutputBody: {
            /** @description 機材の一覧 */
            items: components["schemas"]["ListedItem"][] | null;
        };
        ListedItem: {
            /**
             * Format: date-time
             * @description 投稿時刻
             */
            created_at?: string;
            /**
             * Format: int64
             * @description 機材ID
             * @example 1
             */
            id: number;
            /**
             * @description 分類
             * @example camera
             */
            kind: string;
            /**
             * @description メーカー名
             * @example FUJIFILM
             */
            maker?: string;
            /**
             * @description 機種名
             * @example X-T5
             */
            name: string;
            /**
             * Format: int64
             * @description 作例の件数（反映に遅延がありうる）
             */
            photo_count: number;
        };
        PhotoRef: {
            /** @description キャプション */
            caption: string;
            /**
             * Format: int64
             * @description 写真ID（photo サービスの ID）
             */
            id: number;
            /** @description 画像取得用の署名付きURL。期限付き */
            image_url?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListItems: {
        parameters: {
            query?: {
                /** @description 取得件数 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListItemsOutputBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    CreateItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    GetItemDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 機材ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetItemDetailOutputBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
}
