#!/usr/bin/env bash
# トラフィック分割のローカル予行（#172）。B/G 切替・カナリア重み・（手動）ロールバック・
# 新旧同時稼働を、Caddy の weighted_round_robin と X-Service-Revision ヘッダで測る。
#
#   dev/scripts/traffic-split-drill.sh          # 一式実行
#   OLD_REF=<commit> dev/scripts/traffic-split-drill.sh   # フェーズ e の「旧」を変える
#
# ECS ネイティブ B/G・カナリア（7.2 #63）の前哨。ここで測れないのは
# 「アラームによる自動ロールバック判定」だけで、それが実機再演の本命になる。
#
# 検査（issue #172 の a〜e）:
#   a. B/G 切替はリクエスト断を作らない（切替中も実 API へ連続リクエスト、エラー 0）
#   b. カナリアは重みどおりに分配される（10% ± 許容幅）
#   c. 壊れた版のカナリア: 失敗は重みぶんに閉じ、切り戻しで止まる（失敗数を記録する）
#   e. expand 済みスキーマ上で旧バイナリが正常動作する（新旧同時稼働の前提）
set -eu
cd "$(dirname "$0")/../.."

COMPOSE="docker compose -f deploy/compose/compose.yaml -f deploy/compose/traffic-drill.yaml"
BASE="http://127.0.0.1:8088"
CADDY_DIR="deploy/compose/caddy/drill"
OLD_REF="${OLD_REF:-}" # 空なら「gear_link 列が入る前」の直近コミットを自動で選ぶ

fail=0
ng() { echo "  NG: $*" >&2; fail=1; }
ok() { echo "  ok: $*"; }

tmp=$(mktemp -d)
cleanup() {
  rm -rf "$tmp"
  docker rm -f greenfield-photo-old >/dev/null 2>&1 || true
}
trap cleanup EXIT

# weights <blue> <green>: Caddyfile を生成して Caddy にリロードさせる。
# ECS で言えばターゲットグループの重み変更に相当する操作
weights() {
  mkdir -p "$CADDY_DIR"
  local upstreams="photo-blue:8080 photo-green:8080" policy="lb_policy weighted_round_robin $1 $2"
  # Caddy の weight は正整数のみ。0 は「その版を外す」= upstream から除く（B/G の cutover）
  if [ "$2" = 0 ]; then upstreams="photo-blue:8080"; policy=""; fi
  if [ "$1" = 0 ]; then upstreams="photo-green:8080"; policy=""; fi
  cat > "$CADDY_DIR/Caddyfile" <<EOF
# generated by traffic-split-drill.sh — 編集しない
:80 {
	reverse_proxy $upstreams {
		$policy
		fail_duration 2s
	}
}
EOF
  docker exec greenfield-caddy-drill caddy reload --config /etc/caddy/Caddyfile 2>/dev/null
}

# revision_counts <n>: /healthz を n 回叩き、応答した版の内訳を「blue green error」で返す
revision_counts() {
  local n=$1 blue=0 green=0 err=0 rev
  for _ in $(seq 1 "$n"); do
    rev=$(curl -s -o /dev/null -w '%header{x-service-revision}' --max-time 2 "$BASE/healthz" || echo ERR)
    case "$rev" in
      blue) blue=$((blue + 1)) ;;
      green) green=$((green + 1)) ;;
      *) err=$((err + 1)) ;;
    esac
  done
  echo "$blue $green $err"
}

echo "0. 起動（blue / green 並走、初期重み blue=1 green=0）"
docker build -q -t greenfield/photo:local -f services/photo/Dockerfile . >/dev/null
mkdir -p "$CADDY_DIR"
cat > "$CADDY_DIR/Caddyfile" <<'EOF'
# generated by traffic-split-drill.sh — 編集しない
:80 {
	reverse_proxy photo-blue:8080 {
		fail_duration 2s
	}
}
EOF
$COMPOSE up -d --wait mysql rustfs photo-blue photo-green caddy-drill >/dev/null 2>&1
$COMPOSE up -d flagd >/dev/null 2>&1
CI=1 MODULES=./services/photo mise run --quiet migrate >/dev/null
( cd dev && GOWORK=off go run ./s3admin ensure-buckets >/dev/null )
read -r B G E <<<"$(revision_counts 20)"
[ "$B" = 20 ] && ok "全トラフィックが blue（$B/20）" || ng "初期状態: blue=$B green=$G err=$E"

echo
echo "a. B/G 切替はリクエスト断を作らない"
# 実 API（認証付き読み書き）を流し続けながら blue→green へ一斉切替。
# loadgen はエラーが 1 件でもあれば exit 1 なので、成功 = 断ゼロの証跡になる
( cd dev && GOWORK=off go run ./loadgen -base "$BASE" -duration 12s -rps 20 -quiet > "$tmp/loadgen-a.json" 2>"$tmp/loadgen-a.err" ) &
LG=$!
sleep 4
weights 0 1   # 一斉切替（B/G の cutover 相当）
SWITCHED_AT=$(date +%s)
if wait $LG; then
  ok "切替をまたいだ $(python3 -c 'import json;d=json.load(open("'"$tmp"'/loadgen-a.json"));print(d.get("total") or d.get("requests") or "?")') リクエストが全て成功"
else
  ng "切替中にエラー: $(cat "$tmp/loadgen-a.err" | tail -2) $(cat "$tmp/loadgen-a.json" 2>/dev/null | head -c 200)"
fi
read -r B G E <<<"$(revision_counts 20)"
[ "$G" = 20 ] && ok "切替後は全トラフィックが green（$G/20）" || ng "切替後: blue=$B green=$G err=$E"

echo
echo "b. カナリアは重みどおりに分配される（green 10%）"
weights 9 1
read -r B G E <<<"$(revision_counts 400)"
PCT=$((G * 100 / (B + G)))
if [ "$E" = 0 ] && [ "$PCT" -ge 5 ] && [ "$PCT" -le 15 ]; then
  ok "green の比率 ${PCT}%（green=$G / 400、期待 10%±5）"
else
  ng "分配: blue=$B green=$G err=$E（green ${PCT}%）"
fi

echo
echo "c. 壊れた版のカナリア → 切り戻しで止まる（失敗数を記録）"
# green を「投稿が必ず落ちる版」として再デプロイ（カナリアに壊れた版が来た状況）
PHOTO_FAULT=before_commit $COMPOSE up -d --wait photo-green >/dev/null 2>&1
weights 9 1
TOKEN=$(cd dev && GOWORK=off go run ./devtoken --user drill-canary)
POST_OK=0; POST_FAIL=0
for i in $(seq 1 60); do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 -X POST "$BASE/v2/photos" \
    -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
    -d '{"caption":"drill-c-'"$i"'","content_type":"image/png"}')
  if [ "$code" = 201 ]; then POST_OK=$((POST_OK + 1)); else POST_FAIL=$((POST_FAIL + 1)); fi
done
if [ "$POST_FAIL" -gt 0 ] && [ "$POST_FAIL" -le 12 ]; then
  ok "失敗は重みぶんに閉じる: 60 件中 ${POST_FAIL} 件失敗（期待 ~10%）。**ゼロではない**——アラーム発火までに流れた失敗はカナリアでも消せない"
else
  ng "失敗の出方が想定外: ok=$POST_OK fail=$POST_FAIL"
fi
weights 1 0   # 切り戻し（手動ロールバック。ECS ではアラーム→自動が本命 = 7.2）
ROLLBACK_FAIL=0
for i in $(seq 1 30); do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 -X POST "$BASE/v2/photos" \
    -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
    -d '{"caption":"drill-c-after-'"$i"'","content_type":"image/png"}')
  [ "$code" = 201 ] || ROLLBACK_FAIL=$((ROLLBACK_FAIL + 1))
done
[ "$ROLLBACK_FAIL" = 0 ] && ok "切り戻し後の失敗 0/30（エラーが止まった）" || ng "切り戻し後も失敗: $ROLLBACK_FAIL/30"
# green を健全版に戻しておく
PHOTO_FAULT= $COMPOSE up -d --wait photo-green >/dev/null 2>&1

echo
echo "e. expand 済みスキーマ上で旧バイナリが正常動作する（新旧同時稼働の前提）"
if [ -z "$OLD_REF" ]; then
  # 「gear_link 列の expand を追加したコミットの親」= 旧バイナリはこの列を知らない
  ADDED=$(git log --diff-filter=A --format=%H -- services/photo/migrations/expand/000005_gear_link.up.sql | tail -1)
  OLD_REF=$(git rev-parse "${ADDED}~1" 2>/dev/null || echo "")
fi
[ -n "$OLD_REF" ] || { ng "旧コミットを特定できない（OLD_REF を指定）"; exit "$fail"; }
echo "  旧 = $(git log --format='%h %s' -1 "$OLD_REF")"
git worktree add -f "$tmp/old" "$OLD_REF" >/dev/null 2>&1
docker build -q -t greenfield/photo:old-drill -f "$tmp/old/services/photo/Dockerfile" "$tmp/old" >/dev/null
git worktree remove -f "$tmp/old" >/dev/null 2>&1 || true
docker run -d --name greenfield-photo-old --network greenfield_default \
  -e ENV=dev -e PHOTO_EXTERNAL_ADDR=:8080 -e PHOTO_INTERNAL_ADDR=:8081 -e PHOTO_ADMIN_ADDR=:8082 \
  -e PHOTO_DSN="photo_app:photo_app@tcp(mysql:3306)/photo?parseTime=true" \
  -e LOCALAUTHZ_DSN="localauthz:localauthz@tcp(mysql:3306)/localauthz" \
  -e PHOTO_IMAGE_BUCKET=photo-images -e AWS_REGION=us-east-1 \
  -e AWS_ENDPOINT_URL="http://rustfs:9000" -e AWS_ACCESS_KEY_ID=test -e AWS_SECRET_ACCESS_KEY=testtest \
  greenfield/photo:old-drill >/dev/null
for i in $(seq 1 20); do
  docker exec greenfield-photo-old curl -sf -o /dev/null http://localhost:8080/healthz 2>/dev/null && break
  sleep 1
done
TOKEN_E=$(cd dev && GOWORK=off go run ./devtoken --user drill-old)
create_old() {
  docker exec greenfield-photo-old curl -s -o /dev/null -w '%{http_code}' -X POST http://localhost:8080/v2/photos \
    -H "Authorization: Bearer $TOKEN_E" -H "Content-Type: application/json" \
    -d '{"caption":"drill-e","content_type":"image/png"}'
}
C=$(create_old)
[ "$C" = 201 ] && ok "旧バイナリが新スキーマ（gear_link 列 expand 済み）へ INSERT できる（201）" || ng "旧の投稿: $C"
L=$(docker exec greenfield-photo-old curl -s -o /dev/null -w '%{http_code}' \
  -H "Authorization: Bearer $TOKEN_E" "http://localhost:8080/v2/photos")
[ "$L" = 200 ] && ok "旧バイナリの一覧も 200（SELECT * が新列を無視できる）" || ng "旧の一覧: $L"
ROW=$(docker exec greenfield-mysql mysql -uroot -proot -N photo -e \
  "SELECT gear_link_status IS NULL FROM photos WHERE title='drill-e' ORDER BY id DESC LIMIT 1;" 2>/dev/null)
[ "$ROW" = 1 ] && ok "旧の行は gear_link_status=NULL（新列の既定が効いている）" || ng "行の状態: $ROW"

echo
if [ "$fail" = 0 ]; then echo "すべて期待どおり"; else echo "期待と違う結果がある" >&2; fi
exit "$fail"
