// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type PhotosStatus string

const (
	PhotosStatusPendingUpload PhotosStatus = "pending_upload"
	PhotosStatusReady         PhotosStatus = "ready"
)

func (e *PhotosStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotosStatus(s)
	case string:
		*e = PhotosStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotosStatus: %T", src)
	}
	return nil
}

type NullPhotosStatus struct {
	PhotosStatus PhotosStatus
	Valid        bool // Valid is true if PhotosStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotosStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PhotosStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotosStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotosStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotosStatus), nil
}

type PhotosVisibility string

const (
	PhotosVisibilityPrivate PhotosVisibility = "private"
	PhotosVisibilityPublic  PhotosVisibility = "public"
)

func (e *PhotosVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotosVisibility(s)
	case string:
		*e = PhotosVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotosVisibility: %T", src)
	}
	return nil
}

type NullPhotosVisibility struct {
	PhotosVisibility PhotosVisibility
	Valid            bool // Valid is true if PhotosVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotosVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.PhotosVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotosVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotosVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotosVisibility), nil
}

// 送信予定のイベント。業務データと同一 tx で INSERT（再生の正でもある）
type Outbox struct {
	ID uint64
	// 送信側が採番。受信側 inbox とバスの MessageDeduplicationId で使う
	EventID string
	// 例: photo.published
	EventType string
	// 例: photo:123。バスの MessageGroupId（集約内順序）
	AggregateID string
	Payload     json.RawMessage
	CreatedAt   time.Time
	// NULL = 未送信。relay が送信成功後に記録
	PublishedAt sql.NullTime
	Attempts    int32
	// 指数バックオフの次回試行時刻
	NextAttemptAt sql.NullTime
	// 上限超過はエラー状態として残す（削除しない。監視対象）
	LastError sql.NullString
}

type Photo struct {
	ID           uint64
	OwnerSubject string
	Visibility   PhotosVisibility
	GearItemID   sql.NullInt64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ObjectKey    sql.NullString
	ContentType  sql.NullString
	SizeBytes    sql.NullInt64
	Status       PhotosStatus
	Title        sql.NullString
	// pending / linked / rejected（NULL=要求なし）
	GearLinkStatus sql.NullString
	// 紐付けコマンドの冪等キー（photo が採番）
	GearLinkKey sql.NullString
}
