// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const getPhotoDetail = `-- name: GetPhotoDetail :one

SELECT id, owner_subject, visibility, gear_item_id, created_at, updated_at, object_key, content_type, size_bytes, status, title, gear_link_status, gear_link_key FROM photos WHERE id = ? AND status = 'ready'
`

// 読み側（Read Model）のクエリ。Entity を経由せず応答の形を直接組み立てる。tx 外で実行する。
// 参照できるのは自ドメイン（photo）のテーブルのみ。他ドメインは <name>-client 経由の HTTP か ReplicaView で取得する。
// アップロード未完了（pending_upload）の行は表示経路に出さない。
// SELECT * を使うのは全列を表示に使うため。contract で列を落とせば生成コードが変わり、参照側がコンパイルで落ちる。
// 改名は完了済み。表示は title だけを使う。
// 他の表示クエリと同じく pending_upload は返さない。詳細だけ status を見ていなかったため、
// 画像を上げていない写真に 200 が返り、**存在しないオブジェクトへ署名付き URL を発行**していた
// （ADR 0009 が「有害」と書いた状態そのもの）。オペレータが未完了の行を見るのは一覧（ListPhotos）の役目。
func (q *Queries) GetPhotoDetail(ctx context.Context, id uint64) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhotoDetail, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerSubject,
		&i.Visibility,
		&i.GearItemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.Title,
		&i.GearLinkStatus,
		&i.GearLinkKey,
	)
	return i, err
}

const listPhotos = `-- name: ListPhotos :many
SELECT id, owner_subject, visibility, gear_item_id, created_at, updated_at, object_key, content_type, size_bytes, status, title, gear_link_status, gear_link_key FROM photos ORDER BY created_at DESC LIMIT ?
`

// オペレータ向けの全件一覧（pending も含める。運用上の可視性のため）
func (q *Queries) ListPhotos(ctx context.Context, limit int32) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPhotos, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSubject,
			&i.Visibility,
			&i.GearItemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Title,
			&i.GearLinkStatus,
			&i.GearLinkKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByIDs = `-- name: ListPhotosByIDs :many
SELECT id, owner_subject, visibility, gear_item_id, created_at, updated_at, object_key, content_type, size_bytes, status, title, gear_link_status, gear_link_key FROM photos
WHERE id IN (/*SLICE:ids*/?)
  AND status = 'ready'
  AND (? = '' OR visibility = ?)
ORDER BY created_at DESC
LIMIT ?
`

type ListPhotosByIDsParams struct {
	Ids        []uint64
	Visibility PhotosVisibility
	Limit      int32
}

// 認可付き一覧: ListAccessible で得た ID 群を WHERE IN で絞る。
// visibility の絞り込みと LIMIT は **SQL でやる**。以前はハンドラが Go 側で
// 絞っていたが、件数を切った後に絞るので公開写真が取りこぼされていた（#91 E）。
func (q *Queries) ListPhotosByIDs(ctx context.Context, arg ListPhotosByIDsParams) ([]Photo, error) {
	query := listPhotosByIDs
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Visibility)
	queryParams = append(queryParams, arg.Visibility)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSubject,
			&i.Visibility,
			&i.GearItemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Title,
			&i.GearLinkStatus,
			&i.GearLinkKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByOwner = `-- name: ListPhotosByOwner :many
SELECT id, owner_subject, visibility, gear_item_id, created_at, updated_at, object_key, content_type, size_bytes, status, title, gear_link_status, gear_link_key FROM photos WHERE owner_subject = ? AND status = 'ready' ORDER BY created_at DESC LIMIT ?
`

type ListPhotosByOwnerParams struct {
	OwnerSubject string
	Limit        int32
}

func (q *Queries) ListPhotosByOwner(ctx context.Context, arg ListPhotosByOwnerParams) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPhotosByOwner, arg.OwnerSubject, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSubject,
			&i.Visibility,
			&i.GearItemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Title,
			&i.GearLinkStatus,
			&i.GearLinkKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicPhotosByGearItem = `-- name: ListPublicPhotosByGearItem :many
SELECT id, owner_subject, visibility, gear_item_id, created_at, updated_at, object_key, content_type, size_bytes, status, title, gear_link_status, gear_link_key FROM photos WHERE gear_item_id = ? AND visibility = 'public' AND status = 'ready' ORDER BY created_at DESC LIMIT ?
`

type ListPublicPhotosByGearItemParams struct {
	GearItemID sql.NullInt64
	Limit      int32
}

func (q *Queries) ListPublicPhotosByGearItem(ctx context.Context, arg ListPublicPhotosByGearItemParams) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPublicPhotosByGearItem, arg.GearItemID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerSubject,
			&i.Visibility,
			&i.GearItemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.Title,
			&i.GearLinkStatus,
			&i.GearLinkKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
