// Package gearclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package gearclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for LinkStatus.
const (
	Linked   LinkStatus = "linked"
	Rejected LinkStatus = "rejected"
)

// Valid indicates whether the value is a known member of the LinkStatus enum.
func (e LinkStatus) Valid() bool {
	switch e {
	case Linked:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code 機械可読のエラーコード
	//
	// Examples: photo.not_found
	Code string `json:"code"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	//
	// Examples: Property foo is required but is missing.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	//
	// Examples: https://example.com/error-log/abc123
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	//
	// Examples: 400
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	//
	// Examples: Bad Request
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	//
	// Examples: https://example.com/errors/example
	Type *string `json:"type,omitempty"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// Link defines model for Link.
type Link struct {
	// ItemId 機材ID
	ItemId int64 `json:"item_id"`

	// Key 冪等キー（photo が採番）
	Key string `json:"key"`

	// PhotoId 写真ID（photo サービスの ID）
	PhotoId int64 `json:"photo_id"`

	// Reason rejected の理由（item_not_found 等）
	Reason *string `json:"reason,omitempty"`

	// Status 結果
	Status LinkStatus `json:"status"`
}

// LinkStatus 結果
type LinkStatus string

// LinkPhotoInputBody defines model for LinkPhotoInputBody.
type LinkPhotoInputBody struct {
	// PhotoId 紐付ける写真のID
	PhotoId int64 `json:"photo_id"`
}

// LinkPhotoParams defines parameters for LinkPhoto.
type LinkPhotoParams struct {
	// IdempotencyKey photo が採番する冪等キー。リトライは同じ値で送る
	IdempotencyKey string `json:"Idempotency-Key"`
}

// LinkPhotoJSONRequestBody defines body for LinkPhoto for application/json ContentType.
type LinkPhotoJSONRequestBody = LinkPhotoInputBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// LinkPhotoWithBody 写真と機材を紐付ける（同期コマンド）
	//
	// photo からの同期コマンド。Idempotency-Key ごと結果を永続化し、同じキーの再送には最初の結果を返す（docs/02-architecture.md、4.4）。
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /items/{id}:link-photo (the `LinkPhoto` operationId).
	LinkPhotoWithBody(ctx context.Context, id int64, params *LinkPhotoParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LinkPhoto 写真と機材を紐付ける（同期コマンド）
	//
	// photo からの同期コマンド。Idempotency-Key ごと結果を永続化し、同じキーの再送には最初の結果を返す（docs/02-architecture.md、4.4）。
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /items/{id}:link-photo (the `LinkPhoto` operationId).
	LinkPhoto(ctx context.Context, id int64, params *LinkPhotoParams, body LinkPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPhotoLink 紐付けの受理記録を冪等キーで照会する
	//
	// photo の回収ジョブが pending を確定させるために使う。404 は「コマンドが届いていない」を意味し、同じキーでの再送を促す。.
	//
	// Corresponds with GET /photo-links/{key} (the `GetPhotoLink` operationId).
	GetPhotoLink(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// LinkPhotoWithBody 写真と機材を紐付ける（同期コマンド）
//
// photo からの同期コマンド。Idempotency-Key ごと結果を永続化し、同じキーの再送には最初の結果を返す（docs/02-architecture.md、4.4）。
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /items/{id}:link-photo (the `LinkPhoto` operationId).
func (c *Client) LinkPhotoWithBody(ctx context.Context, id int64, params *LinkPhotoParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLinkPhotoRequestWithBody(c.Server, id, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LinkPhoto 写真と機材を紐付ける（同期コマンド）
//
// photo からの同期コマンド。Idempotency-Key ごと結果を永続化し、同じキーの再送には最初の結果を返す（docs/02-architecture.md、4.4）。
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /items/{id}:link-photo (the `LinkPhoto` operationId).
func (c *Client) LinkPhoto(ctx context.Context, id int64, params *LinkPhotoParams, body LinkPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLinkPhotoRequest(c.Server, id, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPhotoLink 紐付けの受理記録を冪等キーで照会する
//
// photo の回収ジョブが pending を確定させるために使う。404 は「コマンドが届いていない」を意味し、同じキーでの再送を促す。.
//
// Corresponds with GET /photo-links/{key} (the `GetPhotoLink` operationId).
func (c *Client) GetPhotoLink(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPhotoLinkRequest(c.Server, key)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewLinkPhotoRequest calls the generic LinkPhoto builder with application/json body
func NewLinkPhotoRequest(server string, id int64, params *LinkPhotoParams, body LinkPhotoJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLinkPhotoRequestWithBody(server, id, params, "application/json", bodyReader)
}

// NewLinkPhotoRequestWithBody constructs an http.Request for the LinkPhoto method, with any body, and a specified content type
func NewLinkPhotoRequestWithBody(server string, id int64, params *LinkPhotoParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/items/%s:link-photo", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewGetPhotoLinkRequest constructs an http.Request for the GetPhotoLink method
func NewGetPhotoLinkRequest(server string, key string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "key", key, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/photo-links/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// LinkPhotoWithBodyWithResponse 写真と機材を紐付ける（同期コマンド）
	//
	// photo からの同期コマンド。Idempotency-Key ごと結果を永続化し、同じキーの再送には最初の結果を返す（docs/02-architecture.md、4.4）。
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /items/{id}:link-photo (the `LinkPhoto` operationId).
	LinkPhotoWithBodyWithResponse(ctx context.Context, id int64, params *LinkPhotoParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LinkPhotoResponse, error)

	// LinkPhotoWithResponse 写真と機材を紐付ける（同期コマンド）
	//
	// photo からの同期コマンド。Idempotency-Key ごと結果を永続化し、同じキーの再送には最初の結果を返す（docs/02-architecture.md、4.4）。
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /items/{id}:link-photo (the `LinkPhoto` operationId).
	LinkPhotoWithResponse(ctx context.Context, id int64, params *LinkPhotoParams, body LinkPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*LinkPhotoResponse, error)

	// GetPhotoLinkWithResponse 紐付けの受理記録を冪等キーで照会する
	//
	// photo の回収ジョブが pending を確定させるために使う。404 は「コマンドが届いていない」を意味し、同じキーでの再送を促す。.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /photo-links/{key} (the `GetPhotoLink` operationId).
	GetPhotoLinkWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*GetPhotoLinkResponse, error)
}

type LinkPhotoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Link
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LinkPhotoResponse) GetJSON200() *Link {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r LinkPhotoResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r LinkPhotoResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r LinkPhotoResponse) GetApplicationproblemJSON422() *Error {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r LinkPhotoResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r LinkPhotoResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LinkPhotoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LinkPhotoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LinkPhotoResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPhotoLinkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Link
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Error
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *Error
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *Error
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *Error
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPhotoLinkResponse) GetJSON200() *Link {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r GetPhotoLinkResponse) GetApplicationproblemJSON401() *Error {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r GetPhotoLinkResponse) GetApplicationproblemJSON403() *Error {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r GetPhotoLinkResponse) GetApplicationproblemJSON404() *Error {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r GetPhotoLinkResponse) GetApplicationproblemJSON422() *Error {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r GetPhotoLinkResponse) GetApplicationproblemJSON500() *Error {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r GetPhotoLinkResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPhotoLinkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPhotoLinkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPhotoLinkResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// LinkPhotoWithBodyWithResponse 写真と機材を紐付ける（同期コマンド）
//
// photo からの同期コマンド。Idempotency-Key ごと結果を永続化し、同じキーの再送には最初の結果を返す（docs/02-architecture.md、4.4）。
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /items/{id}:link-photo (the `LinkPhoto` operationId).
func (c *ClientWithResponses) LinkPhotoWithBodyWithResponse(ctx context.Context, id int64, params *LinkPhotoParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LinkPhotoResponse, error) {
	rsp, err := c.LinkPhotoWithBody(ctx, id, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLinkPhotoResponse(rsp)
}

// LinkPhotoWithResponse 写真と機材を紐付ける（同期コマンド）
//
// photo からの同期コマンド。Idempotency-Key ごと結果を永続化し、同じキーの再送には最初の結果を返す（docs/02-architecture.md、4.4）。
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /items/{id}:link-photo (the `LinkPhoto` operationId).
func (c *ClientWithResponses) LinkPhotoWithResponse(ctx context.Context, id int64, params *LinkPhotoParams, body LinkPhotoJSONRequestBody, reqEditors ...RequestEditorFn) (*LinkPhotoResponse, error) {
	rsp, err := c.LinkPhoto(ctx, id, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLinkPhotoResponse(rsp)
}

// GetPhotoLinkWithResponse 紐付けの受理記録を冪等キーで照会する
//
// photo の回収ジョブが pending を確定させるために使う。404 は「コマンドが届いていない」を意味し、同じキーでの再送を促す。.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /photo-links/{key} (the `GetPhotoLink` operationId).
func (c *ClientWithResponses) GetPhotoLinkWithResponse(ctx context.Context, key string, reqEditors ...RequestEditorFn) (*GetPhotoLinkResponse, error) {
	rsp, err := c.GetPhotoLink(ctx, key, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPhotoLinkResponse(rsp)
}

// ParseLinkPhotoResponse parses an HTTP response from a LinkPhotoWithResponse call
func ParseLinkPhotoResponse(rsp *http.Response) (*LinkPhotoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LinkPhotoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Link
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetPhotoLinkResponse parses an HTTP response from a GetPhotoLinkWithResponse call
func ParseGetPhotoLinkResponse(rsp *http.Response) (*GetPhotoLinkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPhotoLinkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Link
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}
